export default {
    UPDATE_TEMPERATURE: 'UPDATE_TEMPERATURE',
    ADD_PRODUCT_TO_FREEZER: 'ADD_PRODUCT_TO_FREEZER',
    REMOVE_SCOOP: 'REMOVE_SCOOP',
    PLACE_ORDER: 'PLACE_ORDER',
    FULLFILL_ORDER: 'FULLFILL_ORDER',
    PAY_FOR_ORDER: 'PAY_FOR_ORDER',
    CANCEL_ORDER: 'CANCEL_ORDER',
    FETCH_EMPLOYESS_REQUEST: 'FETCH_EMPLOYESS_REQUEST',    
    FETCH_EMPLOYESS_SUCCESS: 'FETCH_EMPLOYESS_SUCCESS',    
    FETCH_EMPLOYESS_FAILURE: 'FETCH_EMPLOYESS_FAILURE',    
}